// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var Scan = /* module */Block.localModule([], []);

exports.Scan = Scan;
/* No side effect */
