// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function relativizePath(param) {
  var match = atom.project.relativizePath();
  if (match.length !== 2) {
    return /* tuple */[
            "",
            ""
          ];
  } else {
    var projectPath = match[0];
    var relativePath = match[1];
    return /* tuple */[
            projectPath,
            relativePath
          ];
  }
}

exports.relativizePath = relativizePath;
/* No side effect */
