// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var Clipboard = 0;

var Deserializers = 0;

var Views = 0;

var Notifications = 0;

var Config = 0;

var Keymaps = 0;

var Tooltips = 0;

var Commands = 0;

var Grammars = 0;

var Styles = 0;

var CompositeDisposable = 0;

var ScopeDescriptor = 0;

var $$Notification = 0;

var Disposable = 0;

var Decoration = 0;

var Cursor = 0;

var Environment = 0;

var LanguageMode = 0;

var Pane = 0;

var Panel = 0;

var TextEditor = 0;

var TextBuffer = 0;

var TreeSitter = 0;

var $$Selection = 0;

var Package = 0;

var Point = 0;

var DisplayMarker = 0;

var $$Range = 0;

var Type = 0;

exports.Clipboard = Clipboard;
exports.Deserializers = Deserializers;
exports.Views = Views;
exports.Notifications = Notifications;
exports.Config = Config;
exports.Keymaps = Keymaps;
exports.Tooltips = Tooltips;
exports.Commands = Commands;
exports.Grammars = Grammars;
exports.Styles = Styles;
exports.CompositeDisposable = CompositeDisposable;
exports.ScopeDescriptor = ScopeDescriptor;
exports.$$Notification = $$Notification;
exports.Disposable = Disposable;
exports.Decoration = Decoration;
exports.Cursor = Cursor;
exports.Environment = Environment;
exports.LanguageMode = LanguageMode;
exports.Pane = Pane;
exports.Panel = Panel;
exports.TextEditor = TextEditor;
exports.TextBuffer = TextBuffer;
exports.TreeSitter = TreeSitter;
exports.$$Selection = $$Selection;
exports.Package = Package;
exports.Point = Point;
exports.DisplayMarker = DisplayMarker;
exports.$$Range = $$Range;
exports.Type = Type;
/* No side effect */
