// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var Config = /* module */Block.localModule([], []);

var Views = /* module */Block.localModule([], []);

var Grammar = /* module */Block.localModule([], []);

var Packages = /* module */Block.localModule([], []);

var Workspace = /* module */Block.localModule([], []);

var Tooltips = /* module */Block.localModule([], []);

exports.Config = Config;
exports.Views = Views;
exports.Grammar = Grammar;
exports.Packages = Packages;
exports.Workspace = Workspace;
exports.Tooltips = Tooltips;
/* No side effect */
