// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var Packages = /* module */Block.localModule([], []);

var Workspace = /* module */Block.localModule([], []);

exports.Packages = Packages;
exports.Workspace = Workspace;
/* No side effect */
