// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var Scan = /* module */Caml_chrome_debugger.localModule([], []);

exports.Scan = Scan;
/* No side effect */
