// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function setScreenPosition(param, self) {
  self.setScreenPosition(/* array */[
        param[0],
        param[1]
      ]);
  return /* () */0;
}

function setScreenPosition_(param, options, self) {
  self.setScreenPosition(/* array */[
        param[0],
        param[1]
      ], options);
  return /* () */0;
}

function setBufferPosition(param, self) {
  self.setBufferPosition(/* array */[
        param[0],
        param[1]
      ]);
  return /* () */0;
}

function setBufferPosition_(param, options, self) {
  self.setBufferPosition(/* array */[
        param[0],
        param[1]
      ], options);
  return /* () */0;
}

exports.setScreenPosition = setScreenPosition;
exports.setScreenPosition_ = setScreenPosition_;
exports.setBufferPosition = setBufferPosition;
exports.setBufferPosition_ = setBufferPosition_;
/* No side effect */
