// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var Cursor = /* module */Block.localModule([], []);

var Disposable = /* module */Block.localModule([], []);

var CompositeDisposable = /* module */Block.localModule([], []);

var Point = /* module */Block.localModule([], []);

var KeyBinding = /* module */Block.localModule([], []);

var $$Range = /* module */Block.localModule([], []);

var Grammar = /* module */Block.localModule([], []);

var DisplayMarker = /* module */Block.localModule([], []);

var Package = /* module */Block.localModule([], []);

var $$Selection = /* module */Block.localModule([], []);

var Decoration = /* module */Block.localModule([], []);

var TreeSitter = /* module */Block.localModule([], []);

var LanguageMode = /* module */Block.localModule([], []);

var $$Notification = /* module */Block.localModule([], []);

var ScopeDescriptor = /* module */Block.localModule([], []);

var TextBuffer = /* module */Block.localModule([], []);

var TextEditor = /* module */Block.localModule([], []);

var Pane = /* module */Block.localModule([], []);

exports.Cursor = Cursor;
exports.Disposable = Disposable;
exports.CompositeDisposable = CompositeDisposable;
exports.Point = Point;
exports.KeyBinding = KeyBinding;
exports.$$Range = $$Range;
exports.Grammar = Grammar;
exports.DisplayMarker = DisplayMarker;
exports.Package = Package;
exports.$$Selection = $$Selection;
exports.Decoration = Decoration;
exports.TreeSitter = TreeSitter;
exports.LanguageMode = LanguageMode;
exports.$$Notification = $$Notification;
exports.ScopeDescriptor = ScopeDescriptor;
exports.TextBuffer = TextBuffer;
exports.TextEditor = TextEditor;
exports.Pane = Pane;
/* No side effect */
