// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var BufferedNodeProcess = /* module */Caml_chrome_debugger.localModule([], []);

var BufferedProcess = /* module */Caml_chrome_debugger.localModule([], []);

var Clipboard = /* module */Caml_chrome_debugger.localModule([], []);

var Color = /* module */Caml_chrome_debugger.localModule([], []);

var Commands = /* module */Caml_chrome_debugger.localModule([], []);

var CompositeDisposable = /* module */Caml_chrome_debugger.localModule([], []);

var Config = /* module */Caml_chrome_debugger.localModule([], []);

var ContextMenu = /* module */Caml_chrome_debugger.localModule([], []);

var Cursor = /* module */Caml_chrome_debugger.localModule([], []);

var Decoration = /* module */Caml_chrome_debugger.localModule([], []);

var Deserializers = /* module */Caml_chrome_debugger.localModule([], []);

var Directory = /* module */Caml_chrome_debugger.localModule([], []);

var DisplayMarker = /* module */Caml_chrome_debugger.localModule([], []);

var DisplayMarkerLayer = /* module */Caml_chrome_debugger.localModule([], []);

var Disposable = /* module */Caml_chrome_debugger.localModule([], []);

var Dock = /* module */Caml_chrome_debugger.localModule([], []);

var Emitter = /* module */Caml_chrome_debugger.localModule([], []);

var $$File = /* module */Caml_chrome_debugger.localModule([], []);

var GitRepository = /* module */Caml_chrome_debugger.localModule([], []);

var Grammar = /* module */Caml_chrome_debugger.localModule([], []);

var Grammars = /* module */Caml_chrome_debugger.localModule([], []);

var Gutter = /* module */Caml_chrome_debugger.localModule([], []);

var $$History = /* module */Caml_chrome_debugger.localModule([], []);

var KeymapManager = /* module */Caml_chrome_debugger.localModule([], []);

var LayerDecoration = /* module */Caml_chrome_debugger.localModule([], []);

var MarkerLayer = /* module */Caml_chrome_debugger.localModule([], []);

var Menu = /* module */Caml_chrome_debugger.localModule([], []);

var $$Notification = /* module */Caml_chrome_debugger.localModule([], []);

var Notifications = /* module */Caml_chrome_debugger.localModule([], []);

var Package = /* module */Caml_chrome_debugger.localModule([], []);

var Packages = /* module */Caml_chrome_debugger.localModule([], []);

var Pane = /* module */Caml_chrome_debugger.localModule([], []);

var Panel = /* module */Caml_chrome_debugger.localModule([], []);

var PathWatcher = /* module */Caml_chrome_debugger.localModule([], []);

var Point = /* module */Caml_chrome_debugger.localModule([], []);

var Project = /* module */Caml_chrome_debugger.localModule([], []);

var $$Range = /* module */Caml_chrome_debugger.localModule([], []);

var ScopeDescriptor = /* module */Caml_chrome_debugger.localModule([], []);

var $$Selection = /* module */Caml_chrome_debugger.localModule([], []);

var Styles = /* module */Caml_chrome_debugger.localModule([], []);

var Task = /* module */Caml_chrome_debugger.localModule([], []);

var TextBuffer = /* module */Caml_chrome_debugger.localModule([], []);

var TextEditor = /* module */Caml_chrome_debugger.localModule([], []);

var TextEditors = /* module */Caml_chrome_debugger.localModule([], []);

var ThemeManager = /* module */Caml_chrome_debugger.localModule([], []);

var TooltipManager = /* module */Caml_chrome_debugger.localModule([], []);

var Views = /* module */Caml_chrome_debugger.localModule([], []);

var WorkspaceCenter = /* module */Caml_chrome_debugger.localModule([], []);

var Workspace = /* module */Caml_chrome_debugger.localModule([], []);

exports.BufferedNodeProcess = BufferedNodeProcess;
exports.BufferedProcess = BufferedProcess;
exports.Clipboard = Clipboard;
exports.Color = Color;
exports.Commands = Commands;
exports.CompositeDisposable = CompositeDisposable;
exports.Config = Config;
exports.ContextMenu = ContextMenu;
exports.Cursor = Cursor;
exports.Decoration = Decoration;
exports.Deserializers = Deserializers;
exports.Directory = Directory;
exports.DisplayMarker = DisplayMarker;
exports.DisplayMarkerLayer = DisplayMarkerLayer;
exports.Disposable = Disposable;
exports.Dock = Dock;
exports.Emitter = Emitter;
exports.$$File = $$File;
exports.GitRepository = GitRepository;
exports.Grammar = Grammar;
exports.Grammars = Grammars;
exports.Gutter = Gutter;
exports.$$History = $$History;
exports.KeymapManager = KeymapManager;
exports.LayerDecoration = LayerDecoration;
exports.MarkerLayer = MarkerLayer;
exports.Menu = Menu;
exports.$$Notification = $$Notification;
exports.Notifications = Notifications;
exports.Package = Package;
exports.Packages = Packages;
exports.Pane = Pane;
exports.Panel = Panel;
exports.PathWatcher = PathWatcher;
exports.Point = Point;
exports.Project = Project;
exports.$$Range = $$Range;
exports.ScopeDescriptor = ScopeDescriptor;
exports.$$Selection = $$Selection;
exports.Styles = Styles;
exports.Task = Task;
exports.TextBuffer = TextBuffer;
exports.TextEditor = TextEditor;
exports.TextEditors = TextEditors;
exports.ThemeManager = ThemeManager;
exports.TooltipManager = TooltipManager;
exports.Views = Views;
exports.WorkspaceCenter = WorkspaceCenter;
exports.Workspace = Workspace;
/* No side effect */
