// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var HistoryProject = /* module */Caml_chrome_debugger.localModule([], []);

var PathWatcher = /* module */Caml_chrome_debugger.localModule([], []);

var Directory = /* module */Caml_chrome_debugger.localModule([], []);

var GitRepository = /* module */Caml_chrome_debugger.localModule([], []);

var Cursor = /* module */Caml_chrome_debugger.localModule([], []);

var Disposable = /* module */Caml_chrome_debugger.localModule([], []);

var CompositeDisposable = /* module */Caml_chrome_debugger.localModule([], []);

var Point = /* module */Caml_chrome_debugger.localModule([], []);

var KeyBinding = /* module */Caml_chrome_debugger.localModule([], []);

var $$Range = /* module */Caml_chrome_debugger.localModule([], []);

var Grammar = /* module */Caml_chrome_debugger.localModule([], []);

var DisplayMarker = /* module */Caml_chrome_debugger.localModule([], []);

var Package = /* module */Caml_chrome_debugger.localModule([], []);

var $$Selection = /* module */Caml_chrome_debugger.localModule([], []);

var Decoration = /* module */Caml_chrome_debugger.localModule([], []);

var TreeSitter = /* module */Caml_chrome_debugger.localModule([], []);

var LanguageMode = /* module */Caml_chrome_debugger.localModule([], []);

var $$Notification = /* module */Caml_chrome_debugger.localModule([], []);

var ScopeDescriptor = /* module */Caml_chrome_debugger.localModule([], []);

var TextBuffer = /* module */Caml_chrome_debugger.localModule([], []);

var TextEditor = /* module */Caml_chrome_debugger.localModule([], []);

var Panel = /* module */Caml_chrome_debugger.localModule([], []);

var Dock = /* module */Caml_chrome_debugger.localModule([], []);

var WorkspaceCenter = /* module */Caml_chrome_debugger.localModule([], []);

var Workspace = /* module */Caml_chrome_debugger.localModule([], []);

var Pane = /* module */Caml_chrome_debugger.localModule([], []);

exports.HistoryProject = HistoryProject;
exports.PathWatcher = PathWatcher;
exports.Directory = Directory;
exports.GitRepository = GitRepository;
exports.Cursor = Cursor;
exports.Disposable = Disposable;
exports.CompositeDisposable = CompositeDisposable;
exports.Point = Point;
exports.KeyBinding = KeyBinding;
exports.$$Range = $$Range;
exports.Grammar = Grammar;
exports.DisplayMarker = DisplayMarker;
exports.Package = Package;
exports.$$Selection = $$Selection;
exports.Decoration = Decoration;
exports.TreeSitter = TreeSitter;
exports.LanguageMode = LanguageMode;
exports.$$Notification = $$Notification;
exports.ScopeDescriptor = ScopeDescriptor;
exports.TextBuffer = TextBuffer;
exports.TextEditor = TextEditor;
exports.Panel = Panel;
exports.Dock = Dock;
exports.WorkspaceCenter = WorkspaceCenter;
exports.Workspace = Workspace;
exports.Pane = Pane;
/* No side effect */
