// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var Commands = /* module */Block.localModule([], []);

var Views = /* module */Block.localModule([], []);

var Workspace = /* module */Block.localModule([], []);

var Tooltips = /* module */Block.localModule([], []);

exports.Commands = Commands;
exports.Views = Views;
exports.Workspace = Workspace;
exports.Tooltips = Tooltips;
/* No side effect */
